//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDegree
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOwnership
    {
        public int ReportOwnershipID { get; set; }
        public int ReportCode { get; set; }
        public string StudentID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Report Report { get; set; }
    }
}
