//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDegree
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaker
    {
        public int ReportMakerID { get; set; }
        public Nullable<int> ReportCode { get; set; }
        public string ProfessorID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Report Report { get; set; }
    }
}
