//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDegree
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentThesi
    {
        public string StudentID { get; set; }
        public string ThesisCode { get; set; }
    
        public virtual Thesis Thesis { get; set; }
    }
}
